module.exports = {
	label: 'WYSIWYG',
	context: {
		content: '<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ullamcorper nulla non metus auctor fringilla. Etiam porta sem malesuada magna mollis euismod. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Maecenas faucibus mollis interdum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Curabitur blandit tempus porttitor. Vestibulum id ligula porta felis euismod semper.</p>'
	},
	variants: [
		{
			name: 'default'
		},
		{
			name: 'connected',
			context: {
				content: "<h2>Stay Connected</h2><h3>Email</h3><p>All students are assigned a Virginia Community College System (VCCS) e-mail address when they enroll in a class at the College. This e-mail address is the primary e-mail address the College will use for communication with students. Students can access their VCCS student e-mail in their myTyler account once they are enrolled in a class. Students should check their student e-mail regularly for financial aid updates, class information from instructors, reminders about College deadlines and dates, closing and delay notifications, notes from faculty advisors, details on student activities, and many other important messages.</p><h3>Social Media</h3><p>Tap into the Tyler community by connecting with the College on social media. These spaces exist to digitally connect students, faculty and staff, and the community to one another and to Tyler. They tell the Tyler story one post, photo, or video at a time.</p>"
			}
		},
		{
			name: 'involved',
			context: {
				content: "<h2>Get Involved</h2><p><a href>The Student Activities Office</a> provides a variety of educational, cultural, and social experiences for students, faculty, staff and members of the Tyler community. Student activities and organizations are open to all interested students. Students may seek leadership opportunities in Tyler’s Student Government Association.</p><ul><li><strong>Social and Cultural Programs</strong>: The Student Activities Office sponsors movie nights, volunteer projects, intermural sports, guest speakers, sports viewing parties, cardio/fitness classes, game nights and more.</li><li><strong>Clubs and Organizations</strong>: John Tyler Community College offers a diverse selection of student clubs and organizations, and it encourages the formation of new student groups. The College currently recognized more than 35 student clubs and organizations.</li><li><strong>Honorary Organizations</strong>: Phi Theta Kappa International Honor Society Tau Rho (Chester) , Beta Omicron Omicron (Midlothian).</li><li><a href><strong>Intramurals</strong></a>: Basketball, Soccer, and flag football.</li><li><a href><strong>Student Ambassador Program</strong></a>: Tyler’s Student Ambassador Program is a leadership opportunity for Tyler students who are dedicated to serving and representing John Tyler Community College. Student Ambassadors give campus tours, assist prospective and new students, and support various campus events including Open House and New Student Orientation.</li><li><strong>Study Abroad</strong>: John Tyler Community College has a multifaceted international education program aimed at developing global awareness and global learners through international travel presentations and study-abroad opportunities for faculty, staff, and students. These substantive learning opportunities prepare students for possible international employment, international study, and personal enrichment.</li><li><strong>Safe Zone Allies</strong>: The JTCC Safe Zone program supports the College’s vision for a success story for every student, by recruiting, educating and supporting faculty, staff, and students to become allies to the lesbian, gay, bisexual, transgender and queer (LGBTQ) community. Allies learn about LGBTQ issues to promote a safe and supportive environment for people who self-identify as lesbian, gay, bisexual, transgender or queer. By working together members of the LGBTQ community and allies can inspire a spirit of inclusion for all.</li></ul>"
			}
		},
		{
			name: 'tyler-intro',
			context: {
				content: '<figure class="block_right"><img src="//images.fastspot.com/jtcc/344x346/12" alt=""><figcaption>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Nulla vitae elit libero, a pharetra augue.</figcaption></figure><p>Now this robotics champion is heading to Virginia Tech’s prestigious aerospace engineering program on the heels of a summer research internship with the National Science Foundation.</p><h2>See how Tyler pushed him to not lose sight of his biggest goal:</h2><h3>Discover what you’re good at</h3><p>Before coming to Tyler, Ravonte struggled with mechanical engineering even though he was a robotics champion in high school. Looking at the road ahead, he couldn\'t picture himself enjoying the path he was making for himself.</p><p>\"I was at a new school and being flooded with information," Ravonte said. "I wasn\'t getting the best grades. I questioned if it was really something that I should be pursuing."</p><p>Once he transferred to Tyler, he realized that he was in the right field, just in the wrong major.</p><p>He kept his sights set on a career in aerospace. But he switched his major from mechanical engineering to general engineering, saw his GPA skyrocket, and positioned himself for a bachelor\'s in aerospace engineering at Virginia Tech.</p><p>"What has surprised me the most about John Tyler is the level of difficulty of my courses," Ravonte said. "There\'s a stigma that community college is easy, but we learn the same things that four-year colleges teach.</p><p>"I would text my friend who\'s in Virginia Tech\'s engineering program with questions, and the difficulty of our problems would be lining up with the pace of Virginia Tech\'s program," he continued. "That really helps you prepare. I will be going from a two-year to a four-year, and there won\'t be a massive jump in difficulty."</p>'
			}
		},
		{
			name: 'tyler-outro',
			context: {
				content: '<h4>Get the support to succeed</h4><p>Ravonte attributes his renewed self-confidence to Tyler\'s small class sizes and the opportunities to build tight-knit relationships with his classmates and professors.</p><p>He formed independent study groups and never hesitates to reach out to his classmates for late-night problem-solving. And he says his professors go above and beyond to help him understand the material.</p><p>"If you have a question, your professors won\'t just tell you the answer. They will step through the problem with you so that you leave with an understanding behind the answer. Next time you have the problem, you know exactly how to handle it."</p><p>Working closely with his professor and fellow students, Ravonte helped launch Tyler\'s robotics team. He\'s leading the team\'s first project: building an autonomous robot for a competition at Virginia Commonwealth University.</p><h4>Turn your skills ironclad</h4><p>When he noticed a flyer recruiting STEM tutors for Tyler\'s Academic Resource Center, he imagined the payoff right away: Short-term he could quit his off-campus job, and long-term he could become a smarter engineer.</p><p>Now he leads 50+ student tutoring sessions a week for math, science and engineering and offers private tutoring sessions on top of those. He approaches each session differently, adapting his teaching style to how each student learns. Above all, he gets students to adopt helpful time management habits.</p><figure class="quote"><blockquote class="quote_content"><p>Being a tutor has helped me problem solve on my own. If I have a problem now, I go and find the answer. I actually look in a textbook—which I never did before.</p></blockquote><figcaption class="quote_caption"><span class="quote_caption_name">Ravonte Campbell</span></figcaption></figure><p>"I show them how to plan for homework, quizzes and tests in a calendar," Ravonte said. "Then you don\'t have that, \'Oh shoot, I have a test tomorrow, but I also have a four-page paper and six chapters of homework to do.\'</p><p>"Being a tutor has helped me problem solve on my own," he continued. "If I have a problem now, I go and find the answer. I actually look in a textbook—which I never did before."</p><h4>Research with national scientists</h4><p>In his last semester at Tyler, Ravonte was accepted to the National Science Foundation’s Research Experiences for Undergraduates (REU) program. Between graduating from Tyler and heading to VT, he’ll go to Iowa State University and work with a research team analyzing data to determine what skills are critical for entry-level engineers in the aerospace field.</p>'
			}
		},
		{
			name: 'awards',
			context: {
				content: '<p>Each year, John Tyler Community College honors its students for their academic excellence, leadership, school pride, community service and more through its Student Awards Celebration. This year’s ceremony could not be held in person due to the pandemic, so the college announced award winners during a virtual ceremony, shared on social media. More than 60 awards were presented in eleven categories.</p><p>The following award winners were named (zip codes follow recipient names):</p><h2>Sherwood Forest Art & Literary Review</h2><p>John Tyler Community College publishes the Sherwood Forest Art & Literary Review each year in conjunction with its annual student literary and art contest. The publication, which has been highlighting the creativity and talent of Tyler students since 1968, includes four categories: fiction, creative nonfiction, poetry and art. Judges review and select first, second and third place winners in each category and may award honorable mentions. The winning entries are published in the Review. Download an electric copy of the publication.</p><h3>Art</h3><ol><li>Emily Dickson (23192)</li><li>Juanita Zapata (23112)</li><li>Challa Dent (23832)</li></ol><h4>Honorable Mention</h4><ul><li>Erin Walker (23836)</li><li>Diana Rose Penazola (23112)</li></ul><h2>Sherwood Forest Art & Literary Review</h2><p>Each year, Tyler students are given the opportunity to participate in the college’s Social Science Research Expo. During the Expo, students present research they have conducted on a number of topics. This year’s Expo was held virtually, and viewers were asked to vote for their top research projects.</p>'
			}
		}
	]
};
